Tests: Fix compillation of addcinfo
  CC       addcinfo-addcinfo.o
addcinfo.c: In function 'main':
addcinfo.c:74: warning: implicit declaration of function 'read'
addcinfo.c:74: error: 'STDIN_FILENO' undeclared (first use in this function)
addcinfo.c:74: error: (Each undeclared identifier is reported only once
addcinfo.c:74: error: for each function it appears in.)
addcinfo.c:102: warning: implicit declaration of function 'write'
addcinfo.c:102: error: 'STDOUT_FILENO' undeclared (first use in this function)

The manaul page for function read/write says that the header file unistd.h
needs to be included. This header file was indirectly included on Linux
but it was not included on FreeBSD. It is better to include it directly
and do not rely on other header files.

Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>