libcm: Include missing header file signal.h
The man 3 signal says that header file signal.h need to be included
for function kill(). This header file was included indirectly on Linux.
But it was not included on FreeBSD

  CC       libcm_a-subproc.o
subproc.c: In function 'cm_subproc_done':
subproc.c:232: warning: implicit declaration of function 'kill'
subproc.c:232: error: 'SIGKILL' undeclared (first use in this function)
subproc.c:232: error: (Each undeclared identifier is reported only once
subproc.c:232: error: for each function it appears in.)

Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>