Include missing header file
The header file stdint.h was probably included by other
header file on fedora.

In file included from src/ipa.c:41:0:
src/srvloc.h:23:2: error: unknown type name 'uint16_t'
  uint16_t port;

configure was executed with following parameters
CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -fexceptions
        -fstack-protector-strong --param=ssp-buffer-size=4
        -grecord-gcc-switches -m64 -mtune=generic -Wall -Wextra
        -Wno-unused-parameter -g3 -O0'
    --libexecdir=/usr/lib --with-tmpdir=/var/run/certmonger
    --enable-systemd --enable-pie --enable-now --enable-tmpfiles

Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>